pygments: true
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, Vagrantfile]
host: http://www.nearinfinity.com
markdown: kramdown
hideFromHomepage: []
jobs_whitelist:
  Mobile: [iphone, ios, ipad, android, mobile]
  'Big Data': [hadoop, lucene, database, orm]
  Rails: [rails, ruby, grails]
  Node: [node]
  Java: [java, groovy, jruby, ant]
  '.Net': [.net]
  Agile: [agile]
  Web: [web, javascript, css]

